server:
  port: 8086
  shutdown: graceful

spring:
  application:
    name: Hands-On-With-Security-JWT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret-key: ee4629ad8ad409d48794d9ee353cb0e66d127b3aed2d58c6cc3b1ab29d886df3
    expiration-time: 84600